from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import pandas as pd
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
import time

# ----------------------------------------------------------------
# PRODUCTION FASTAPI SERVER
# Run with: uvicorn 2_run_api:app --reload
# ----------------------------------------------------------------

# Initialize FastAPI app (This information appears in the Swagger UI)
app = FastAPI(
    title="🎬 AI Movie Recommendation API",
    description="Semantic search engine powered by BERT and FAISS.",
    version="1.0.0"
)

# Global dictionary to hold models in RAM
SYSTEM_DATA = {
    "df": None,
    "faiss_index": None,
    "model": None
}

# Run this function once when the server starts
@app.on_event("startup")
async def load_models():
    print("⏳ System starting: Loading models and database into RAM...")
    try:
        # Read the files generated by '1_build_engine.py'
        SYSTEM_DATA["df"] = pd.read_csv('data/processed_movies.csv')
        SYSTEM_DATA["faiss_index"] = faiss.read_index('data/vector_index.index')
        SYSTEM_DATA["model"] = SentenceTransformer('all-MiniLM-L6-v2')
        print("✅ System successfully initialized! Ready to accept requests.")
    except Exception as e:
        print(f"❌ CRITICAL ERROR: Could not load data. Ensure you ran 1_build_engine.py first. Details: {e}")

# Define the expected format for incoming client requests
class SearchQuery(BaseModel):
    query_text: str
    num_results: int = 5

# --- API ENDPOINTS ---

@app.get("/")
async def root():
    return {
        "message": "API is online! 🚀", 
        "docs_url": "http://127.0.0.1:8000/docs"
    }

@app.post("/api/recommend")
async def get_recommendations(query: SearchQuery):
    """
    Analyzes the user's text and returns the most semantically similar movies.
    """
    if SYSTEM_DATA["model"] is None or SYSTEM_DATA["faiss_index"] is None:
        raise HTTPException(status_code=503, detail="Server is currently loading AI models, please wait.")
    
    if not query.query_text.strip():
        raise HTTPException(status_code=400, detail="Query text cannot be empty.")

    start_time = time.time()

    try:
        # 1. Convert text to vector (Deep Learning)
        query_vector = SYSTEM_DATA["model"].encode([query.query_text]).astype('float32')
        faiss.normalize_L2(query_vector)
        
        # 2. Perform ultra-fast search in FAISS
        distances, indices = SYSTEM_DATA["faiss_index"].search(query_vector, query.num_results)
        
        # 3. Format the results
        results = []
        for i, idx in enumerate(indices[0]):
            movie = SYSTEM_DATA["df"].iloc[idx]
            results.append({
                "rank": i + 1,
                "title": str(movie['original_title']),
                "similarity_score_pct": round(float(distances[0][i]) * 100, 2),
                "genres": str(movie['genres']) if 'genres' in movie else "Unknown",
                "overview": str(movie['overview'])
            })
            
        processing_time_ms = round((time.time() - start_time) * 1000, 2)
        
        # Return JSON response
        return {
            "success": True,
            "query": query.query_text,
            "processing_time_ms": processing_time_ms,
            "recommendations": results
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Search failed: {str(e)}")